export const featureRegistry = [
  {
    key: "Sequence_Length",
    label: "Sequence Length",
    group: "Sequence",
    unit: "aa/bp",
    desc: "Sequence length (amino acids or base pairs).",
    applicable_omics: ["GENOME", "TRANSCRIPTOME", "PROTEOME"],
  },
  {
    key: "GC_Content_Percent",
    label: "GC%",
    group: "Sequence",
    unit: "%",
    desc: "GC content percentage.",
    applicable_omics: ["GENOME"],
  },
  {
    key: "C_N_Ratio",
    label: "C:N Ratio",
    group: "Ratios",
    unit: "",
    desc: "Carbon to nitrogen ratio.",
    applicable_omics: ["GENOME", "TRANSCRIPTOME"],
  },
  {
    key: "Protein_ID",
    label: "Protein ID",
    group: "Identifier",
    unit: "",
    desc: "Unique protein identifier.",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "pI",
    label: "Isoelectric Point",
    group: "PhysChem",
    unit: "",
    desc: "Isoelectric point.",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "GRAVY",
    label: "GRAVY",
    group: "PhysChem",
    unit: "",
    desc: "Grand average of hydropathy.",
    applicable_omics: ["PROTEOME"],
    alias: ["Hydrophobicity"],
  },
  {
    key: "Instability_Index",
    label: "Instability Index",
    group: "PhysChem",
    unit: "",
    desc: "Instability index (values > 40 often considered unstable).",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "Helix_Propensity",
    label: "Helix Propensity",
    group: "Structure",
    unit: "",
    desc: "Helix tendency.",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "Sheet_Propensity",
    label: "Sheet Propensity",
    group: "Structure",
    unit: "",
    desc: "Sheet tendency.",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "Turn_Propensity",
    label: "Turn Propensity",
    group: "Structure",
    unit: "",
    desc: "Turn tendency.",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "Disulfide_Potential",
    label: "Disulfide Potential",
    group: "Structure",
    unit: "",
    desc: "Disulfide potential indicator.",
    applicable_omics: ["PROTEOME"],
  },
  {
    key: "C",
    label: "Carbon Atoms",
    group: "Elements",
    unit: "atoms",
    desc: "Carbon atom count.",
    applicable_omics: ["GENOME", "PROTEOME"],
  },
  {
    key: "N",
    label: "Nitrogen Atoms",
    group: "Elements",
    unit: "atoms",
    desc: "Nitrogen atom count.",
    applicable_omics: ["GENOME", "PROTEOME"],
  },
];

export const featureGroups = ["Identifier", "Sequence", "Elements", "Ratios", "PhysChem", "Structure"];
